services:
  - type: web
    name: primerly-biovagon
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --limit-request-line 16384
    pythonVersion: 3.10.13 